# Generated by Django 5.0.1 on 2024-02-23 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HuggingFaceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model_name_or_path', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Classification', 'Classification'), ('Ner', 'Ner')], max_length=14)),
                ('train_nlp_dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.nlpdataset')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingArgs',
            fields=[
                ('hugging_face_model', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nlp.huggingfacemodel')),
                ('learning_rate', models.FloatField()),
                ('per_device_train_batch_size', models.IntegerField()),
                ('per_device_eval_batch_size', models.IntegerField()),
                ('num_train_epochs', models.IntegerField()),
                ('weight_decay', models.FloatField()),
                ('evaluation_strategy', models.CharField(max_length=5)),
                ('save_strategy', models.CharField(max_length=5)),
                ('load_best_model_at_end', models.BooleanField()),
            ],
        ),
    ]
