# Generated by Django 5.0.1 on 2024-01-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0002_nlptext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='nlptext',
            name='labels',
        ),
        migrations.AddField(
            model_name='nlptext',
            name='labels',
            field=models.ManyToManyField(to='nlp.label'),
        ),
    ]
